const kanjiData = [
    { question: '店を構える', answer: '店をかまえる' },
    { question: 'お米に石が混じる', answer: 'まじる' },
    { question: '再びあやまちを繰り返さない', answer: 'ふたたび' },
    { question: 'アルバイトで毎月のしゅうにゅうが増えた。', answer: '収入' },
    { question: '線を引くためにじょうぎを使う。', answer: '定規' },
    { question: '消防隊が川でおぼれた人をきゅうじょした。', answer: '救助' },
    { question: '夕方になって、お菓子がはんがくになった。', answer: '半額' },
    { question: '父は毎朝ちょうかんを読んでいる。', answer: '朝刊' },
    { question: '小さい頃からなれしたしんだ町を歩いた。', answer: '慣れ親しんだ' },
    { question: '山の風がこころよい気分だった。', answer: '快い' },
    { question: '友達を家にまねいて遊んだ。', answer: '招いて' },
    { question: '兄は大学で学問をおさめている。', answer: '修めて' },
    { question: '使ったおもちゃを箱にきちんとおさめる。', answer: '収める' },
    { question: '運動会では色々なきょうぎが行われた。', answer: '競技' },
    { question: '早ね早起きのしゅうかんをつけたい。', answer: '習慣' },
    { question: '久しぶりに小学校のきゅうゆうに会った。', answer: '旧友' },
];
